"""empty message

Revision ID: 028784642567
Revises: 05157e24d59d
Create Date: 2023-04-02 22:37:32.009682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '028784642567'
down_revision = '05157e24d59d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isotdel', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('isotdel')

    # ### end Alembic commands ###
