"""empty message

Revision ID: bb974ab25f1a
Revises: 6f80ad6c00be
Create Date: 2023-04-16 22:47:33.324800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb974ab25f1a'
down_revision = '6f80ad6c00be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor_request', schema=None) as batch_op:
        batch_op.drop_constraint('visitor_request_requestId_fkey', type_='foreignkey')
        batch_op.drop_constraint('visitor_request_visitorId_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'visitor', ['visitorId'], ['visitorID'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'request', ['requestId'], ['requestID'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor_request', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('visitor_request_visitorId_fkey', 'visitor', ['visitorId'], ['visitorID'])
        batch_op.create_foreign_key('visitor_request_requestId_fkey', 'request', ['requestId'], ['requestID'])

    # ### end Alembic commands ###
